### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mschilli87** [NoSuck/MuttMailto#1]
I came across [your blog post about this script](https://nosuck.org/2015/08/02/configuring-mailto-in-an-xdg-environment) and I was wondering if you would mind clarifying the license in case I want to build on top of it.

**Comment by mschilli87** [comment]
Nevermind, [I just read the comments](https://nosuck.org/2015/08/02/configuring-mailto-in-an-xdg-environment/#comment-21). :wink:

Never tried it myself so far (I did *not* know that I wanted to :wink:) but when I read your post it struck my like a good idea and instead of trying to do it myself or using my brain when reading, I just decided to use your solution without noticing the obvious. :laughing:

**Comment by NoSuck** [comment]
Thank you for making me realize that post was missing an update at the top.  I shouldn't have bashed the basic idea just because of a syntactical slip-up, though.  It's actually good security!  The authors of mutt must have agreed, because the functionality outlined in that post has since been incorporated as the [`mailto_allow`](http://www.mutt.org/doc/manual/#mailto-allow) directive.

The license would have been WTFPL.
